hydra:
  run:
    dir: '.'

dataset:
  train_manifest_path: /mnt/d/datasets/noisy_aug/train_manifest.json
  valid_manifest_path: /mnt/d/datasets/noisy_aug/valid_manifest.json
  test_manifest_path:
  random_seed: 42
model:
  model:
    waveshaper_config:
      threshold: 15.0
    compressor_config:
      sample_rate: 16000
      threshold: -10.0
      ratio: 30.0
      makeup: 0.0
      attack: 1.0e-7
      release: 1.0e-3
      downsample_factor: 2.0
    equalizer_config:
        n_frequency_bins: 1000
    noise_config:
        n_frequency_bins: 1000
  optim:
    lr: 5.0e-4
    mode: min
    factor: 0.1
    patience: 5
    cooldown: 0
    eps: 1.0e-7
    interval: epoch
  run:
    distributed: False
run:
  num_gpus: 1
  epochs: 100
  batch_size: 4
  logs_dir: logs/